### ISSUE TITLE
not working on zoom (app)

### ISSUE THREAD

**Issue by mmm7761** [CatxFish/obs-virtual-cam#86] opened 2020-04-02 17:47 UTC
i selected the right cam but it doesn't work on zoom
![zoome](https://user-images.githubusercontent.com/60720685/78281309-773de080-74e8-11ea-8480-65de2daffa5f.JPG)
![zoomer](https://user-images.githubusercontent.com/60720685/78281312-773de080-74e8-11ea-943d-9c64b125fae1.JPG)

**Comment by electromage** [comment] 2020-04-02 21:23
I just tried this also, VLC can open the stream but Windows Camera and Zoom cannot.

**Comment by warnerwes** [comment] 2020-04-02 23:21
Same for me. Zoom isn't working with the Virtual Camera since the latest update. It's probably a new security feature. Snap Camera still works with zoom, but not the OBS Virtual Camera.

**Comment by beeblebrox** [comment] 2020-04-02 23:40
I can confirm this happened for me as well as of the latest zoom update that happened today.  Zoom still works with Virtual Camera.  Thought I'd be sneaky and use Virtual Camera by using the OBS as the source there, but Virtual Camera won't list OBS virtual camera, I never tried and I don't know if it is a related issue.

**Comment by crossan007** [comment] 2020-04-03 01:40
Zoom issue is only on the latest zoom version.

One dll is causing the issue.

See this thread https://github.com/CatxFish/obs-virtual-cam/issues/78#issuecomment-603482332

**Comment by EMREOYUN** [comment] 2020-04-03 08:48
Confirmed, also not working

**Comment by aoanla** [comment] 2020-04-03 08:57
Can people please stop adding me toos on this issue! Look at issue 78 for actual discussion on this and stop duplicating issues!

**Comment by EMREOYUN** [comment] 2020-04-03 09:17
@aoanla No one pinged you.

**Comment by EMREOYUN** [comment] 2020-04-03 09:47
> Zoom issue is only on the latest zoom version.
> 
> One dll is causing the issue.
> 
> See this thread [#78 (comment)](https://github.com/CatxFish/obs-virtual-cam/issues/78#issuecomment-603482332)

Ok-zoomer patch worked well.

**Comment by aoanla** [comment] 2020-04-03 10:31
> @aoanla No one pinged you.

You're right, but it's utterly pointless having multiple issues on the same problem and people contributing to all of them, rather than the lead. (The developer should close at least some of these as duplicates.)

**Comment by EMREOYUN** [comment] 2020-04-03 11:04
> > @aoanla No one pinged you.
> 
> You're right, but it's utterly pointless having multiple issues on the same problem and people contributing to all of them, rather than the lead. (The developer should close at least some of these as duplicates.)

Right.

**Comment by Algram** [comment] 2020-04-03 12:59
Can anyone confirm if the same thing is happening with the desktop App of Microsoft Teams? I am having a similar issue on the linux side: https://github.com/CatxFish/obs-v4l2sink/issues/25

**Comment by 3vi1** [comment] 2020-04-04 22:19
@Algram:  Yes, I can confirm the same thing is happing with the Teams desktop app.  I just built and and installed everything.  VLC shows the v4l2loopback stream fine, but Teams only shows a black window.  

Other video redirection to Teams from ffmpeg and gstreamer is working fine here, so there's something that Teams specifically doesn't like about the obs-virtual-cam output.

**Comment by KovalevArtem** [comment] 2020-05-01 19:04
@mmm7761The problem is resolved in the latest versions of ZOOM. You can close the question...

**Comment by KovalevArtem** [comment] 2020-05-01 19:04
@mmm7761 The problem is resolved in the latest versions of ZOOM. You can close the question...

**Closed** 2020-06-11 22:22 UTC
